name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - tbd
#      - tc_nightly
#      - tc_v*.*.*
#  pull_request:
#    branches: [ "master", "develop" ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build Docker amd64 image
      run: docker buildx build --platform linux/amd64 . --tag revvox/teddycloud-amd64:$(date +%s) --tag revvox/teddycloud:latest
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Build Docker arm64 image
      run: docker buildx build --platform linux/arm64 . --tag revvox/teddycloud-arm64:$(date +%s) --tag revvox/teddycloud-arm64:latest
  build-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm
    - name: Build Docker arm image
      run: docker buildx build --platform linux/arm . --tag revvox/teddycloud-arm:$(date +%s) --tag revvox/teddycloud-arm:latest
  build-s390x:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: s390x
    - name: Build Docker s390x image
      run: docker buildx build --platform linux/s390x . --tag revvox/teddycloud-s390x:$(date +%s) --tag revvox/teddycloud-s390x:latest
